### ISSUE TITLE
Compatibility with minimal theme | List items in preview misaligned

### ISSUE THREAD

**Issue by patowod** [Arch-Storm/obsidian-indent-lines#2]
Hi there, 
I may have found a bug in conjunction with kepanos minimal theme and described it over at https://forum.obsidian.md/t/minimal-theme/3659/348?u=woody so the theme author is also aware of this. Just wanted to let you know. :)

![](https://forum.obsidian.md/uploads/default/original/2X/d/d8aec3911f57de9d14f76401afa33ae03b5ce579.jpeg)

**Comment by Arch-Storm** [comment]
Seems to be fixed by the theme, as it includes similar functionality, so I will close this.
