### ISSUE TITLE
Indentation lines not taking effect

### ISSUE THREAD

**Issue by zephaniahong** [Arch-Storm/obsidian-indent-lines#6]
Hi!

I installed your plugin but it does not seem to be doing anything when I am making lists. My lists look the same as before.
Also, I do not see the Indentation Lines plugin under my plugin options after downloading. Is that normal? I've tried uninstalling and re-installing to no avail.

Any help would be appreciated!
Thank you!

**Comment by kevinwcyu** [comment]
It only works with the dark theme.

**Comment by kevinwcyu** [comment]
@zephaniahong it only works with the dark theme.
